---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute  # TODO(aaronmondal): Use GRPCRoute after resolution of
                 # https://github.com/TraceMachina/nativelink/issues/481
metadata:
  name: cache-route
spec:
  parentRefs:
    - sectionName: cache
      name: cache
  rules:
    - backendRefs:
        - name: nativelink-cas
          port: 50051
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute # TODO(aaronmondal): Pure GRPC is unstable here. Find out why
                #                    and migrate to a GRPCRoute.
metadata:
  name: scheduler-route
spec:
  parentRefs:
    - sectionName: scheduler
      name: scheduler
  rules:
    - backendRefs:
        - name: nativelink-scheduler
          port: 50052
